### ISSUE TITLE
No messages being received on command port in 4s.  Possible encryption problem

### ISSUE THREAD

**Issue by yanxinyuan** [chef/opscode-pushy-client#105]
Platform = Centos 6
Push Job Server Version = 2.1.0
Push Job Client Version =  2.1.1
Chef Client Version = 12.13.37

I have uploaded push job cookbook to my chef-server, and use chef-client command to configure push job client on my machine, but the node status by searching from the server always shows unavailable, when i search the log from /var/log/chef-push-jobs-client/current, it show the error below:
```
2016-09-29_08:57:36.73327 INFO: [delta.chef.client2] Starting reconfigure thread.  Will reconfigure / reload keys after 3600 seconds, less up to splay 0.1.
2016-09-29_08:57:36.73332 INFO: [delta.chef.client2] Starting heartbeat / offline detection thread on interval 10.0 ...
2016-09-29_08:57:40.75176 ERROR: [delta.chef.client2] No messages being received on command port in 4s.  Possible encryption problem?
2016-09-29_08:57:40.75203 INFO: [delta.chef.client2] Reconfiguring client / reloading keys ...
2016-09-29_08:57:40.75220 INFO: [delta.chef.client2] Retrieving configuration from https://delta.chef.server/organizations/delta//pushy/config/delta.chef.client2: ...
2016-09-29_08:57:41.75311 INFO: [delta.chef.client2] Stopping command / server heartbeat receive thread and destroying sockets ...
2016-09-29_08:57:41.87677 INFO: [delta.chef.client2] Resolved delta.chef.server to '172.22.27.61' and 2 others

```
And here is the debug log detail:
INFO: [delta.chef.client2] Resolved delta.chef.server to '172.22.27.61' and 2 others
INFO: [delta.chef.client2] Resolved delta.chef.server to '172.22.27.61' and 2 others
INFO: [delta.chef.client2] Starting ZMQ version {:major=>4, :minor=>0, :patch=>5}
INFO: [delta.chef.client2] Starting ZMQ version {:major=>4, :minor=>0, :patch=>5}
INFO: [delta.chef.client2] Listening for server heartbeat at tcp://delta.chef.server:10000
INFO: [delta.chef.client2] Listening for server heartbeat at tcp://delta.chef.server:10000
INFO: [delta.chef.client2] Connecting to command channel at tcp://delta.chef.server:10002
INFO: [delta.chef.client2] Connecting to command channel at tcp://delta.chef.server:10002
INFO: [delta.chef.client2] Considering server online, and starting to heartbeat
INFO: [delta.chef.client2] Considering server online, and starting to heartbeat
INFO: [delta.chef.client2] Started client.
INFO: [delta.chef.client2] Started client.
INFO: [delta.chef.client2] Starting reconfigure thread.  Will reconfigure / reload keys after 3600 seconds, less up to splay 0.1.
INFO: [delta.chef.client2] Starting command / server heartbeat receive thread ...
INFO: [delta.chef.client2] Starting heartbeat / offline detection thread on interval 10.0 ...
INFO: [delta.chef.client2] Starting reconfigure thread.  Will reconfigure / reload keys after 3600 seconds, less up to splay 0.1.
INFO: [delta.chef.client2] Starting heartbeat / offline detection thread on interval 10.0 ...
DEBUG: [delta.chef.client2] Sending heartbeat (sequence #1)
DEBUG: [delta.chef.client2] Sending heartbeat (sequence #1)
INFO: [delta.chef.client2] Starting command / server heartbeat receive thread ...
INFO: [delta.chef.client2] Sending heartbeat 1 (logging first 3)
INFO: [delta.chef.client2] Sending heartbeat 1 (logging first 3)
ERROR: [delta.chef.client2] No messages being received on command port in 4s.  Possible encryption problem?
ERROR: [delta.chef.client2] No messages being received on command port in 4s.  Possible encryption problem?
INFO: [delta.chef.client2] Reconfiguring client / reloading keys ...
INFO: [delta.chef.client2] Reconfiguring client / reloading keys ...

**Comment by yanxinyuan** [comment]
The issue seems in the wrong place, close it.

**Comment by laxmanrapolu** [comment]
What is the solution for this problem. I am also facing the same problem.
