### ISSUE TITLE
User or client 'xinyuan' does not have access to that action on this server

### ISSUE THREAD

**Issue by yanxinyuan** [chef/opscode-pushy-client#106]
Platform = Centos 6
Push Job Server Version = 2.1.0
Push Job Client Version = 2.1.1
Chef Client Version = 12.13.37

When i installed my chef station, 'xinyuan' is my default user by using command "chef-server-ctl user-create" generated, and i can use command "knife node status" to  check the nodes status,  but after i use the below commands to create a new client and groups. 
knife client create rundeck-push-jobs
knife group create pushy_job_readers
knife group create pushy_job_writers
knife group add client rundeck-push-jobs pushy_job_readers
knife group add client rundeck-push-jobs pushy_job_writers

I can't use "knife node status" command any more, it always occurs the below error:
[root@delta chef-repo]# knife node status
ERROR: You authenticated successfully to https://delta.chef.server/organizations/delta as xinyuan but you are not authorized for this action
Response:  User or client 'xinyuan' does not have access to that action on this server.

**Comment by yanxinyuan** [comment]
after i executing below commands, this issue has been fixed.
knife group add user xinyuan pushy_job_readers
knife group add user xinyuan pushy_job_writers

**Comment by scalp42** [comment]
thanks a lot for sharing the fix @yanxinyuan
