### ISSUE TITLE
push-client cannot connect to server due to SSL error (windows)

### ISSUE THREAD

**Issue by docwhat** [chef/opscode-pushy-client#62]
On Windows the push-client can't connect to the chef-server due to an SSL
error.

The chef-server has a Thawte certificate and it works fire on Windows for
chef-client.

`pushy-client.log` has this in it:

    [2015-07-14T16:23:29-04:00] INFO: Pushy Client Service initialized
    [2015-07-14T16:23:39-04:00] INFO: Pushy version: 1.1.3
    [2015-07-14T16:23:42-04:00] INFO: [lark-windows02] Using node name: lark-windows02
    [2015-07-14T16:23:42-04:00] INFO: [lark-windows02] Using Chef server: https://chef-server.example.com/organizations/example
    [2015-07-14T16:23:42-04:00] INFO: [lark-windows02] Using private key: C:\chef\client.pem
    [2015-07-14T16:23:42-04:00] INFO: [lark-windows02] Using org name: example
    [2015-07-14T16:23:42-04:00] INFO: [lark-windows02] Incarnation ID: 3ac8735a-9935-4e04-a5f8-9bdd5b1a1a54
    [2015-07-14T16:23:42-04:00] INFO: [lark-windows02] Starting client ...
    [2015-07-14T16:23:42-04:00] INFO: [lark-windows02] Retrieving configuration from https://chef-server.example.com/organizations/example/pushy/config/lark-windows02 ...
    [2015-07-14T16:23:42-04:00] ERROR: SSL Validation failure connecting to host: chef-server.example.com - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
    [2015-07-14T16:23:42-04:00] ERROR: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

`chef-stacktrace.out` has this:

    OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
    C:/opscode/pushy/embedded/lib/ruby/1.9.1/net/http.rb:800:in `connect'
    C:/opscode/pushy/embedded/lib/ruby/1.9.1/net/http.rb:800:in `block in connect'
    C:/opscode/pushy/embedded/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
    C:/opscode/pushy/embedded/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
    C:/opscode/pushy/embedded/lib/ruby/1.9.1/net/http.rb:800:in `connect'
    C:/opscode/pushy/embedded/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
    C:/opscode/pushy/embedded/lib/ruby/1.9.1/net/http.rb:745:in `start'
    C:/opscode/pushy/embedded/lib/ruby/1.9.1/net/http.rb:1285:in `request'
    C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8-x86-mingw32/lib/chef/http/basic_client.rb:65:in `request'
    C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8-x86-mingw32/lib/chef/http.rb:257:in `block in send_http_request'
    C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8-x86-mingw32/lib/chef/http.rb:289:in `retrying_http_errors'
    C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8-x86-mingw32/lib/chef/http.rb:251:in `send_http_request'
    C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8-x86-mingw32/lib/chef/http.rb:141:in `request'
    C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8-x86-mingw32/lib/chef/rest.rb:115:in `get'
    C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client.rb:172:in `get_config'
    C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client.rb:72:in `start'
    C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/windows_service.rb:72:in `block in service_main'
    <internal:prelude>:10:in `synchronize'
    C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/windows_service.rb:54:in `service_main'
    C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/win32-service-0.8.2/lib/win32/daemon.rb:301:in `mainloop'
    C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/win32-service-0.8.2/lib/win32/daemon.rb:202:in `mainloop'
    C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/windows_service.rb:235:in `<main>'

Just to show that whatever is wrong is in the embedded ruby with
push-jobs-client and that the chef embedded ruby is fine:

``` ps1
PS C:\opscode\pushy> C:\opscode\chef\embedded\bin\ruby.exe -ropen-uri -e "p open('https://chef-server.example.com/').read.length"
8745
PS C:\opscode\pushy> C:\opscode\pushy\embedded\bin\ruby.exe -ropen-uri -e "p open('https://chef-server.example.com/').read.length"
C:/opscode/pushy/embedded/lib/ruby/1.9.1/net/http.rb:800:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/opscode/pushy/embedded/lib/ruby/1.9.1/net/http.rb:800:in `block in connect'
        from C:/opscode/pushy/embedded/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
        from C:/opscode/pushy/embedded/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
        from C:/opscode/pushy/embedded/lib/ruby/1.9.1/net/http.rb:800:in `connect'
        from C:/opscode/pushy/embedded/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
        from C:/opscode/pushy/embedded/lib/ruby/1.9.1/net/http.rb:745:in `start'
        from C:/opscode/pushy/embedded/lib/ruby/1.9.1/open-uri.rb:306:in `open_http'
        from C:/opscode/pushy/embedded/lib/ruby/1.9.1/open-uri.rb:775:in `buffer_open'
        from C:/opscode/pushy/embedded/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
        from C:/opscode/pushy/embedded/lib/ruby/1.9.1/open-uri.rb:201:in `catch'
        from C:/opscode/pushy/embedded/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
        from C:/opscode/pushy/embedded/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
        from C:/opscode/pushy/embedded/lib/ruby/1.9.1/open-uri.rb:677:in `open'
        from C:/opscode/pushy/embedded/lib/ruby/1.9.1/open-uri.rb:33:in `open'
        from -e:1:in `<main>'
PS C:\opscode\pushy>
```

**Comment by docwhat** [comment]
Okay, I can make my ruby command by running this instead:

```
C:\opscode\pushy\embedded\bin\ruby.exe -ropen-uri -e "ENV['SSL_CERT_FILE'] = 'C:/opscode/chef/embedded/ssl/certs/cacert.pem' ; p open('https://chef-server.bigdatalab.ibm.com/').read.length"
```

I notice that the `c:\opscode\pushy\embedded\` directory doesn't have a `ssl/` subdirectory.  Copying it over isn't enough to make it work, alas.

The versions of OpenSSL is different too... chef has `1.0.0l` and pushy has `1.0.0k` -- though I doubt that's the problem. :cry:

**Comment by afiune** [comment]
@docwhat What you need to do in this case is to append that cert into `/opt/chef/embedded/ssl/certs/cacert.pem` 

NOTE: If you are using `chefdk` then the path is `/opt/chefdk/embedded/ssl/certs/cacert.pem`

Let me know if that solved your problem! :smile:
