### ISSUE TITLE
Issue with push-jobs client stability since upgrading from 1.x to 2.1.0 on RHEL 7

### ISSUE THREAD

**Issue by trevorlauder** [chef/opscode-pushy-client#94]
I upgraded from push-jobs 1.x to 2.1.0 and since then have been having issues where the clients become 'unavailable' and throw this error:

```
INFO: [fqdn] Reconfiguring client / reloading keys ...
INFO: [fqdn] Retrieving configuration from https://chef-server-fqdn/organizations/myorg//pushy/config/fqdn: ...
INFO: [fqdn] No key returned from server; falling back to 1.x protocol (no encryption)
INFO: [fqdn] Stopping command / server heartbeat receive thread and destroying sockets ...
INFO: [fqdn] Resolved chef-server-fqdn to '10.1.1.1' and 0 others
INFO: [fqdn] Starting ZMQ version {:major=>4, :minor=>0, :patch=>5}
INFO: [fqdn] Listening for server heartbeat at tcp://chef-server-fqdn:10000
INFO: [fqdn] Connecting to command channel at tcp://chef-server-fqdn:10002
INFO: [fqdn] Stopping heartbeat / offline detection thread ...
INFO: [fqdn] Starting command / server heartbeat receive thread ...
INFO: [fqdn] Considering server online, and starting to heartbeat
INFO: [fqdn] Stopping reconfigure thread ...
INFO: [fqdn] Reconfigured client.
INFO: [fqdn] Forced GC; Stat count changed 1
INFO: [fqdn] Starting reconfigure thread.  Will reconfigure / reload keys after 3600 seconds, less up to splay 0.1.
INFO: [fqdn] Starting heartbeat / offline detection thread on interval 1.0 ...
INFO: [fqdn] Received server heartbeat (sequence #31933) logging 0/3
INFO: [fqdn] Received server heartbeat (sequence #31934) logging 1/3
INFO: [fqdn] Received server heartbeat (sequence #31935) logging 2/3
INFO: [fqdn] Received server heartbeat (sequence #31936) logging 3/3
ERROR: [fqdn] No messages being received on command port in 4s.  Possible encryption problem?
```

The client then reconnects and repeats.  The clients are connecting to the 1.x server and have `allow_unencrypted true` set.

As an FYI, we are using the following cookbook versions:

chef-client 4.6.0
push-jobs 3.1.0

**Comment by echohack** [comment]
Hey @trevorlauder What platforms are you seeing this on?

**Comment by trevorlauder** [comment]
RHEL 7

**Comment by HappyRainy** [comment]
We having the same issue.

`ERROR: [ip-0A0B0B1B] No messages being received on command port in 674s.  Possible encryption problem?
ERROR: [ip-0A0B0B1B] No messages being received on command port in 675s.  Possible encryption problem?
ERROR: [ip-0A0B0B1B] No messages being received on command port in 676s.  Possible encryption problem?
ERROR: [ip-0A0B0B1B] Error in command / server heartbeat receive thread: can't create Thread: Not enough space
C:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client.rb:143:in `initialize'
C:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client.rb:143:in `new'
C:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client.rb:143:in `trigger_reconfigure'
C:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client/protocol_handler.rb:294:in `block in start_receive_thread'
ERROR: [ip-0A0B0B1B] No messages being received on command port in 677s.  Possible encryption problem?
ERROR: [ip-0A0B0B1B] Error in command / server heartbeat receive thread: can't create Thread: Not enough space
C:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client.rb:143:in `initialize'
C:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client.rb:143:in `new'
C:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client.rb:143:in `trigger_reconfigure'
C:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client/protocol_handler.rb:294:in `block in start_receive_thread'`

We have to restart the Push Client service then.

The platform is Windows 2012

Thanks
Jing

**Comment by gliptak** [comment]
Are the clocks synch-ed between the nodes and the Chef server?

**Comment by trevorlauder** [comment]
@gliptak Yes, and I have since reverted all of the clients back to the 1.x version and everything works fine.

**Comment by gliptak** [comment]
@trevorlauder I see. We might have to consider downgrading to 1.x too ...

**Comment by sandeepkumarbn** [comment]
ports need to open 10000 & 10002 & 10003

**Comment by virendra1205** [comment]
Guys, 

do we have any solution for this, I am also facing same problem.

**Comment by AnamikaN** [comment]
> Are the clocks synch-ed between the nodes and the Chef server?

how to sync the clocks, my client is in PST and server is in UTC.
