### ISSUE TITLE
list of job states?

### ISSUE THREAD

**Issue by gliptak** [chef/opscode-pushy-client#96]
I might have missed this in the documentation, but I couldn't find a list of job states (and their transitions, which might be trivial in this case) documented.

Reading https://github.com/chef/opscode-pushy-client/blob/master/lib/pushy_client/job_runner.rb the list seem to be:
+ idle
+ running
+ committed

**Comment by gliptak** [comment]
My logs now also captured:
+ voting

**Comment by gliptak** [comment]
Also ```timed_out```

**Comment by srenatus** [comment]
[It seems to be in the server's docs](https://github.com/chef/opscode-pushy-server/blob/3b461f327a2f052cda67dae572e269a605c0b673/docs/rest-api-summary.txt#L10-L11), which [seem to be accurate](https://github.com/chef/opscode-pushy-server/blob/3b461f327a2f052cda67dae572e269a605c0b673/apps/pushy/include/pushy_sql.hrl#L26-L34):

```erlang
-type job_status() :: new |
                      voting |
                      running |
                      complete |
                      quorum_failed |
                      crashed |
                      aborted |
                      timed_out.
```

**Comment by gliptak** [comment]
@srenatus Thank you for the pointer.
